export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_ERROR = "GET_PROJECTS_ERROR";

export const INIT_PAGINATION = "INIT_PAGINATION";
export const NEXT_PAGINATION = "NEXT_PAGINATION";
export const PREV_PAGINATION = "PREV_PAGINATION";

export const GET_DETAIL_PROJECTS = "GET_DETAIL_PROJECTS";
export const GET_DETAIL_PROJECTS_SUCCESS = "GET_DETAIL_PROJECTS_SUCCESS";
export const GET_DETAIL_PROJECTS_ERROR = "GET_DETAIL_PROJECTS_ERROR";

export const SELECTED_FAVOURITE_PROJECT = "SELECTED_FAVOURITE_PROJECT";
export const DESELECTED_FAVOURITE_PROJECT = "DESELECTED_FAVOURITE_PROJECT";
export const SET_FAVOURITE_SUCCESS = "SET_FAVOURITE_SUCCESS";
export const SET_FAVOURITE_ERROR = "SET_FAVOURITE_ERROR";


export const DELETED_PROJECT = "DELETED_PROJECT";
export const DELETED_PROJECT_SUCCESS = "DELETED_PROJECT_SUCCESS";
export const DELETED_PROJECT_ERROR = "DELETED_PROJECT_ERROR";