export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_ERROR = "GET_PROJECTS_ERROR";

export const INIT_PAGINATION = "INIT_PAGINATION";
export const NEXT_PAGINATION = "NEXT_PAGINATION";
export const PREV_PAGINATION = "PREV_PAGINATION";

export const GET_DETAIL_PROJECTS = "GET_DETAIL_PROJECTS";
export const GET_DETAIL_PROJECTS_SUCCESS = "GET_DETAIL_PROJECTS_SUCCESS";
export const GET_DETAIL_PROJECTS_ERROR = "GET_DETAIL_PROJECTS_ERROR";
