const Projects = [
  {
    project: {
      id: 32946,
      lastUpdated: "2020-06-09",
      title: "Autonomous Systems and Operations",
      acronym: "ASO",
      status: "Active",
      startDate: "Oct 2014",
      endDate: "Sep 2021",
      description:
        "<p>The AES Autonomous Systems and Operations (ASO) project will develop an understanding of the impacts of increasing communication time delays on mission operations, develop autonomy technologies to mitigate the impacts, and infuse them into Human Exploration and Operations systems. The technologies are expected to reduce operations costs as well. This technology has been tested on ISS in FY14-16 as part of the AES Autonomous Mission Operations project; testing continues in FY19-20 under ASO. This technology has also been tested in the Integrated Power, Avionics and Software (IPAS) facility at JSC, and in a testing facility during Exploration Flight Test 1 (EFT-1); tests continue under ASO with ISS and Orion systems and also target infusion into the Artemis-2 mission.<br /> <br /> This project incorporates and builds on the results from the AES Autonomous Mission Operations project.<br /> <br /> Future human spaceflight missions will occur with crews and spacecraft at large distances, with long communication delays to the Earth. The one-way light-time delay to the Moon is 1.3 seconds, which is sufficient to make some scenarios (e.g., landing) difficult or impossible to conduct from Earth. One-way communication delays to human exploration destinations such as Near Earth Asteroids (NEAs) range from seconds to minutes. The one-way light-time delay to Mars ranges from 3 minutes (at conjunction) to 22 minutes (at opposition). As the communication delays increase, the crews in the spacecraft must execute, and manage, much of the mission themselves. Throughout the course of a mission, as distances increase, NASA must continue to migrate operations functionality from the remote Mission Control Center flight control room to the vehicle for use by the crew. The role of the ground control teams and systems will evolve away from real-time support to a more long-range planning, diagnosis, analysis, and prognostics support role, while the vehicle systems and crew must take on the role of onboard daily schedule execution, planning, and systems management. Both ground and vehicle systems will require automation to maximize crew functionality, minimize unnecessary overhead, and reduce operating costs. This project is to understand the impacts of increasing communications time delays on operations and to develop technologies to mitigate the impacts.</p> ",
      benefits:
        "<p>Currently Funded NASA Missions: This technology has the potential to improve the ability of astronauts to perform activities onboard the International Space Station (ISS) more efficiently, thereby increasing their productivity.</p>  <p>Planned NASA missions: This technology is critical to enable human spaceflight missions beyond Low Earth Orbit.</p>  <p>Commercial Space industry: As new companies begin commercial human space operations, be they tourists in Low Earth Orbit or sending crew to and from the Moon, this technology can provide the same benefits of more efficient operations and increased productivity that it provides to NASA.</p> ",
      technologyMaturityStart: "5",
      technologyMaturityCurrent: "7",
      technologyMaturityEnd: "8",
      destinations: ["Earth", "The Moon", "Mars"],
      supportedMissionType: "Projected Mission (Pull)",
      responsibleProgram: "Advanced Exploration Systems Division",
      responsibleMissionDirectorateOrOffice:
        "Human Exploration and Operations Mission Directorate",
      leadOrganization: {
        name: "Ames Research Center",
        type: "NASA Center",
        acronym: "ARC",
        city: "Moffett Field",
        state: "CA",
        country: "United States",
      },
      workLocations: ["Alabama", "California", "Texas"],
      programDirectors: ["Christopher L Moore"],
      projectManagers: ["Jeremy D Frank"],
      website: "",
      libraryItems: [
        {
          id: 59041,
          title: "AMOEXPRESS",
          type: "Image",
          description:
            "Astronaut Jeff Williams performs AMO EXPRESS demonstration onboard ISS, 2016.",
          externalUrl: null,
          publishedBy: null,
          publishedDate: null,
          files: [
            {
              id: 39664,
              url: "https://techport.nasa.gov/file/39664",
              size: 185264,
            },
          ],
        },
        {
          id: 59040,
          title: "Autonomous startup of an Experiment Rack on ISS",
          type: "Story",
          description:
            "<p>The ASO project completed a demonstration of autonomous system software configuring an experiment rack onboard the International Space Station. Currently, the power-on and configuration of the EXPRESS Rack are performed by flight controllers on Earth, and are separate core and payload procedures, requiring many synchronized steps. AMO-EXPRESS 2.0 demonstrated that all of the necessary steps can be executed automatically by astronauts.  This demonstration provided important insight into how future astronauts can manage their spacecraft without assistance from Earth-based mission control.</p>  <p>This project is described in the following publication:<br /> <br /> H. Stetson, J. Frank, A. Haddock, R. Cornelius; L. Wang; L. Garner. AMO EXPRESS: A Command and Control Experiment for Crew Autonomy. Proceedings of the AIAA Conference on Space Operations, September 2015.</p> ",
          externalUrl: null,
          publishedBy: "AES staff",
          publishedDate: "Dec 2016",
          files: [
            {
              id: 39663,
              url: "https://techport.nasa.gov/file/39663",
              size: 464547,
            },
          ],
        },
        {
          id: 59044,
          title: "IPAS",
          type: "Image",
          description:
            "Vehicle Systems Automation testing in Integrated Power Avionics and Software (iPAS) facility, Johnson Space Center, 2017.",
          externalUrl: null,
          publishedBy: null,
          publishedDate: null,
          files: [
            {
              id: 39667,
              url: "https://techport.nasa.gov/file/39667",
              size: 769522,
            },
          ],
        },
        {
          id: 59046,
          title:
            "Jeremy Frank gives Invited Talk on ASO at the 2017 Innovative Applications of Artificial Intelligence (IAAI) Conference",
          type: "Link",
          description: null,
          externalUrl:
            "http://videolectures.net/aaai2017_frank_space_mission/?q=Jeremy%20Frank",
          publishedBy: null,
          publishedDate: null,
          files: [],
        },
        {
          id: 59045,
          title: "Jeremy Frank on the NASA Silicon Valley Podcast (2017)",
          type: "Link",
          description: null,
          externalUrl: "https://www.nasa.gov/ames/nisv-podcast-Jeremy-Frank",
          publishedBy: null,
          publishedDate: null,
          files: [],
        },
        {
          id: 59047,
          title: "NASA Television Interview: ‘Water Works’ (2014)",
          type: "Link",
          description: null,
          externalUrl: "https://www.youtube.com/watch?v=MtUz5WfA2dw",
          publishedBy: null,
          publishedDate: null,
          files: [],
        },
        {
          id: 59042,
          title: "OrionSim",
          type: "Image",
          description:
            "Astronauts Reid Weisman and Drew Morgan evaluate new caution and warning technology during Orion cockpit simulation.",
          externalUrl: null,
          publishedBy: null,
          publishedDate: null,
          files: [
            {
              id: 39665,
              url: "https://techport.nasa.gov/file/39665",
              size: 2318833,
            },
          ],
        },
        {
          id: 59048,
          title:
            "Smithsonian Magazine article (2017) describing projects including Autonomous Systems and Operations",
          type: "Link",
          description: null,
          externalUrl:
            "http://www.smithsonianmag.com/science-nature/when-we-go-mars-will-we-want-2001-space-odysseys-hal-9000-us-180963694/",
          publishedBy: null,
          publishedDate: null,
          files: [],
        },
        {
          id: 59039,
          title: "Success Story - Advanced Caution and Warning System",
          type: "Story",
          description:
            "<p>Demonstration of Advanced Caution and Warning System Software with the Orion EFT-1 flight and subsequent ongoing evaluation for fault management of Orion.<br /> <br /> ASO developed Advanced Caution and Warning (ACAWS) software to assist flight controllers and astronauts in identifying and responding to faults.  This technology was first demonstrated during the Exploration Flight Test 1 (EFT-1) mission; the software provided flight controllers with insight into EFT-1 performance throughout the 6+ hour mission.  Subsequently, the software has been matured to provide the same insight for astronauts, and has been scaled to run on embedded processors such as those onboard spacecraft.  It has been employed in joint simulations with flight controllers and astronauts in preparation for Exploration Mission 1 (EM-1).<br /> <br /> This work is described in the following publications:</p>  <p>Gordon B. Aaseng and Eric Barszcz and Henry Valdez and Haifa Moses. Scaling Up Model-Based Diagnostic and Fault Effects Reasoning for Spacecraft.  Proceedings of the AIAA Conference on Spac Operations, September 2016.</p>  <p>G. Aaseng, J. Frank. Transitioning Autonomous Systems Technology Research to a Flight Software Environment.  Proceedings of the AIAA Conference on Spac Operations, September 2016.<br /> <br /> Gordon B. Aaseng, Adam Sweet, and John Ossenfort. Performance Analysis of an Autonomous Fault Management System.  Proceedings of the 2018 AIAA SPACE and Astronautics Forum and Exposition, 2018 </p> ",
          externalUrl: null,
          publishedBy: "AES staff",
          publishedDate: "Dec 2016",
          files: [
            {
              id: 39662,
              url: "https://techport.nasa.gov/file/39662",
              size: 300190,
            },
          ],
        },
        {
          id: 59049,
          title:
            "Success Story - Demonstration of Autonomous Vehicle Systems Management",
          type: "Story",
          description:
            "<p>Demonstration of Autonomous Vehicle Systems Management software, in conjunction with a novel avionics architecture, power systems architecture, and life support system.  <br /> <br /> NASA has developed and demonstrated multiple technologies to enable the autonomous operation of a dormant space habitat. These technologies included a fault-tolerant avionics architecture, novel spacecraft power system and power system controller, and autonomy software to control the habitat.  The demonstration involved simulation of the habitat and multiple spacecraft sub-systems (power storage and distribution, avionics, and air-side life-support) during a multi-day test at NASA’s Johnson Space Center. The foundation of the demonstration was ‘quiescent operations’ of a habitat during a 55 minute eclipse period. For this demonstration, the spacecraft power distribution system and air-side life support system were simulated at a high level of fidelity; additional systems were managed, but with lower fidelity operational constraints and system behavior. Operational constraints for real and simulated loads were developed by analyzing on-orbit hardware and evaluating future Exploration capable technology. A total of 13 real and simulated loads were used during the test. Eight scenarios including both nominal and off- nominal conditions were performed.<br /> This accomplishment is described in the following paper:<br /> <br /> G. Aaseng, J. Frank, M. Iatauro, C. Knight, R. Levinson, John Ossenfort, M. Scott, A. Sweet, J. Csank, J. Soeder, A. Loveless, D, Carrejo, T. Ngo, Z. Greenwood. Development and Testing of a Vehicle Management System for Autonomous Spacecraft Habitat Operations.  Proceedings of the AIAA Space Conference, 2018. </p> ",
          externalUrl: null,
          publishedBy: "",
          publishedDate: null,
          files: [],
        },
        {
          id: 59043,
          title: "TOCASSC",
          type: "Image",
          description:
            "Astronaut Reid Wiseman demonstrates autonomous operations software onboard ISS, September 2015.",
          externalUrl: null,
          publishedBy: null,
          publishedDate: null,
          files: [
            {
              id: 39666,
              url: "https://techport.nasa.gov/file/39666",
              size: 1411279,
            },
          ],
        },
      ],
      closeoutSummary: "",
      supportingOrganizations: [
        {
          name: "Johnson Space Center",
          type: "NASA Center",
          acronym: "JSC",
          city: "Houston",
          state: "TX",
          country: "United States",
        },
        {
          name: "Marshall Space Flight Center",
          type: "NASA Center",
          acronym: "MSFC",
          city: "Huntsville",
          state: "AL",
          country: "United States",
        },
      ],
      primaryTas: [
        {
          id: 10720,
          code: "TX07",
          title: "Exploration Destination Systems",
          priority: null,
        },
        {
          id: 10732,
          code: "TX07.3",
          title: "Mission Operations and Safety",
          priority: null,
        },
        {
          id: 10734,
          code: "TX07.3.2",
          title: "Integrated Flight Operations Systems",
          priority: null,
        },
      ],
      additionalTas: [],
    },
  },
  {
    project: {
      id: 94227,
      lastUpdated: "2020-06-05",
      title: "UAS Traffic Management",
      acronym: "UTM",
      status: "Active",
      startDate: "Oct 2015",
      endDate: "Sep 2021",
      description:
        "<p>Unmanned Aircraft Systems (UAS) Traffic Management (or UTM) develops and validates airspace operational and integration performance requirements to enable safe, large-scale UAS operations in low-altitude airspace.</p> ",
      benefits:
        "<p>UTM will provide guidance and a set of validated requirements including a proof-of-concept prototype for managing low-altitude airspace in a safe and efficient manner that will be designed to be compatible with existing and expected future systems and regulations. UTM is predicted to have a large impact on facilitating the improvement of the certification process by the FAA.</p> ",
      technologyMaturityStart: "3",
      technologyMaturityCurrent: "4",
      technologyMaturityEnd: "6",
      destinations: ["Earth"],
      responsibleProgram: "Airspace Operations and Safety Program",
      responsibleMissionDirectorateOrOffice:
        "Aeronautics Research Mission Directorate",
      leadOrganization: {
        name: "Ames Research Center",
        type: "NASA Center",
        acronym: "ARC",
        city: "Moffett Field",
        state: "CA",
        country: "United States",
      },
      workLocations: [
        "Alaska",
        "California",
        "North Dakota",
        "Nevada",
        "New York",
        "Ohio",
        "Texas",
        "Virginia",
      ],
      programDirectors: ["Akbar Sultan"],
      projectManagers: ["Ronald D Johnson"],
      website: "https://utm.arc.nasa.gov/",
      libraryItems: [],
      closeoutSummary: "",
      closeoutDocuments: [],
      supportingOrganizations: [
        {
          name: "AirMap",
          type: "Industry",
          acronym: null,
          city: "",
          state: "",
          country: null,
        },
        {
          name: "Amazon",
          type: "Industry",
          acronym: null,
          city: null,
          state: null,
          country: null,
        },
        {
          name: "ANRA Technologies",
          type: "Industry",
          acronym: null,
          city: "Tysons",
          state: "VA",
          country: "United States",
        },
        {
          name: "Armstrong Flight Research Center",
          type: "NASA Center",
          acronym: "AFRC",
          city: "Edwards",
          state: "CA",
          country: "United States",
        },
        {
          name: "Federal Aviation Administration",
          type: "U.S. Government",
          acronym: "FAA",
          city: "Washington",
          state: "DC",
          country: "United States",
        },
        {
          name: "General Electric",
          type: "Industry",
          acronym: "GE",
          city: "Boston",
          state: "MA",
          country: "United States",
        },
        {
          name: "Glenn Research Center",
          type: "NASA Center",
          acronym: "GRC",
          city: "Cleveland",
          state: "OH",
          country: "United States",
        },
        {
          name: "Google",
          type: "Industry",
          acronym: null,
          city: "Mountain View",
          state: "CA",
          country: "United States",
        },
        {
          name: "Intel",
          type: "Industry",
          acronym: null,
          city: null,
          state: null,
          country: null,
        },
        {
          name: "Langley Research Center",
          type: "NASA Center",
          acronym: "LaRC",
          city: "Hampton",
          state: "VA",
          country: "United States",
        },
        {
          name: "Rockwell Collins",
          type: "Industry",
          acronym: null,
          city: null,
          state: null,
          country: null,
        },
        {
          name: "Simulyze",
          type: "Industry",
          acronym: null,
          city: "",
          state: "",
          country: null,
        },
      ],
      primaryTas: [
        {
          id: 10961,
          code: "TX16",
          title: "Air Traffic Management and Range Tracking Systems",
          priority: null,
        },
        {
          id: 10962,
          code: "TX16.1",
          title: "Safe All Vehicle Access",
          priority: null,
        },
      ],
      additionalTas: [
        {
          id: 10961,
          code: "TX16",
          title: "Air Traffic Management and Range Tracking Systems",
          priority: null,
        },
        {
          id: 10964,
          code: "TX16.3",
          title: "Traffic Management Concepts",
          priority: null,
        },
      ],
    },
  },
  {
    project: {
      id: 11692,
      lastUpdated: "2020-06-05",
      title: "Bigelow Expandable Activity Module Project",
      acronym: "BEAM",
      status: "Active",
      startDate: "Jan 2013",
      endDate: "May 2022",
      description:
        '<p>The Bigelow Expandable Activity Module (BEAM) project is a NASA-industry partnership with Bigelow Aerospace (BA) that developed the first human-rated expandable (also called "inflatable") space habitat for demonstration on the International Space Station (ISS). The partnership offers NASA substantial cost savings for technology development and for future exploration missions that could use commercially-provided expandable structures and habitats.</p>  <p>The BEAM project advances expandable habitat technology by conducting a flight demonstration of a commercially-designed expandable system to achieve Technology Readiness Level 9.0. The primary performance requirement is to demonstrate that the BEAM can successfully launch and berth to the ISS, deploy and expand, and maintain long-term pressure without leakage. The leak performance is defined as both short-term, immediately after deployment, and long-term, for the balance of the mission.</p>  <p>BEAM was successfully launched on SpaceX CRS-8 (April 8, 2016), berthed to ISS Node 3 Aft and pressurized on May 28 2016.  BEAM successfully completed leak testing and the first crew ingress was June 6, 2016.  BEAM, originally certified for a two-year life, has been functioning as expected and in November 2018 NASA and Bigelow Aerospace authorized BEAM for utilization as a stowage module and extended the mission life to the end-of-ISS life.</p>  <p>The demonstration consists of the following critical technology objectives:</p>  <p>- Launch of a packed expandable structure in a Commercial Resupply Services (CRS) launch vehicle<br /> - Safe deployment (expansion) on ISS<br /> - Passive air exchange with ISS and an environment inside the BEAM supporting periodic, temporary ingress by the ISS crew<br /> - Measure deployment loads during expansion of the BEAM on ISS<br /> - Determine radiation protection capability of an expandable structure in low-Earth orbit and demonstrate the performance of advanced active radiation sensors on ISS<br /> - Long-term structural performance of expandable shell after exposure to atomic oxygen, vacuum, radiation, and thermal cycling<br /> - Demonstrate performance of structural health monitoring systems<br /> - Measure long-term leak performance of expandable bladder and bladder joints after launch and deployment cycle<br /> - Develop structural and mechanical system requirements for a human-rated expandable module in an external orbital environment and successfully verify those requirements.<br /> - Develop crew restraints and mobility aids for Intravehicular Activity (IVA) inside an expandable module.<br /> - Develop and implement "housekeeping" procedures for internal surfaces of an expandable module.</p>  <p>-Demonstrate utilization as a stowage module.</p>  <p>For more information, see the following links below:</p>  <p>BEAM Advanced Exploration Systems (AES) Project Overview</p>  <p><a href="https://www.nasa.gov/content/bigelow-expandable-activity-module">https://www.nasa.gov/content/bigelow-expandable-activity-module</a></p>  <p>NASA Extends BEAM\'s Time on the International Space Station</p>  <p><a href="https://www.nasa.gov/feature/nasa-extends-beam-s-time-on-the-international-space-station">https://www.nasa.gov/feature/nasa-extends-beam-s-time-on-the-international-space-station</a></p>  <p>BEAM First Year On-Orbit (May 26, 2017)</p>  <p><a href="https://www.nasa.gov/feature/first-year-of-beam-demo-offers-valuable-data-on-expandable-habitats">https://www.nasa.gov/feature/first-year-of-beam-demo-offers-valuable-data-on-expandable-habitats</a></p>  <p>BEAM Stowage Utilization and Life Extension (October 2, 2017)</p>  <p><a href="https://www.nasa.gov/feature/nasa-may-extend-beam-s-time-on-the-international-space-station">https://www.nasa.gov/feature/nasa-may-extend-beam-s-time-on-the-international-space-station</a></p>  <p>BEAM Facts, Figures, FAQs (July 17, 2017)</p>  <p><a href="https://www.nasa.gov/feature/beam-facts-figures-faqs">https://www.nasa.gov/feature/beam-facts-figures-faqs</a></p>  <p>BEAM Overview (March 12, 2015)</p>  <p><a href="https://www.nasa.gov/content/new-expandable-addition-on-space-station-to-gather-critical-data-for-future-space-habitat">https://www.nasa.gov/content/new-expandable-addition-on-space-station-to-gather-critical-data-for-future-space-habitat</a></p>  <p> </p> ',
      benefits:
        "<p>The NASA-Bigelow partnership enables both partners to learn how to develop, launch, install, and test expandable structures, all at substantial cost savings relative to either party doing these things alone. The BEAM project develops structural and mechanical system requirements for a human-rated expandable module in an external orbital environment and verifies those requirements. After BEAM installation on the ISS, NASA will gain valuable insight into the performance of an expandable module in orbit.</p>  <p> </p> ",
      technologyMaturityStart: "7",
      technologyMaturityCurrent: "9",
      technologyMaturityEnd: "9",
      destinations: ["The Moon", "Mars", "Others Inside the Solar System"],
      supportedMissionType: "Projected Mission (Pull)",
      responsibleProgram: "Advanced Exploration Systems Division",
      responsibleMissionDirectorateOrOffice:
        "Human Exploration and Operations Mission Directorate",
      leadOrganization: {
        name: "Johnson Space Center",
        type: "NASA Center",
        acronym: "JSC",
        city: "Houston",
        state: "TX",
        country: "United States",
      },
      workLocations: [
        "California",
        "Colorado",
        "District of Columbia",
        "Nevada",
        "Texas",
        "Virginia",
      ],
      programDirectors: ["Christopher L Moore"],
      projectManagers: ["Gerard D Valle"],
      principalInvestigators: ["Gerard D Valle"],
      coInvestigators: [
        "Nathan D Wells",
        "John Iovine",
        "Dan J Fry",
        "Michael S Grygier",
      ],
      website:
        "https://www.nasa.gov/content/bigelow-expandable-activity-module",
      libraryItems: [
        {
          id: 58322,
          title: "BEAM",
          type: "Image",
          description: "Inside View of BEAM Module Mockup",
          externalUrl: null,
          publishedBy: null,
          publishedDate: null,
          files: [
            {
              id: 39054,
              url: "https://techport.nasa.gov/file/39054",
              size: 1407024,
            },
          ],
        },
        {
          id: 58321,
          title: "BEAM Mockup",
          type: "Image",
          description: "Bigelow Expandable Activity Module (BEAM) Mockup",
          externalUrl: null,
          publishedBy: null,
          publishedDate: null,
          files: [
            {
              id: 39053,
              url: "https://techport.nasa.gov/file/39053",
              size: 871957,
            },
          ],
        },
        {
          id: 58328,
          title: "BEAM om ISS",
          type: "Image",
          description: "BEAM om ISS Node 3 Aft",
          externalUrl: null,
          publishedBy: null,
          publishedDate: null,
          files: [
            {
              id: 39059,
              url: "https://techport.nasa.gov/file/39059",
              size: 137553,
            },
          ],
        },
        {
          id: 58329,
          title: "Expedition 47 Crew inside of BEAM",
          type: "Image",
          description: "Expedition 47 Crew inside of BEAM",
          externalUrl: null,
          publishedBy: null,
          publishedDate: null,
          files: [
            {
              id: 39060,
              url: "https://techport.nasa.gov/file/39060",
              size: 2062115,
            },
          ],
        },
        {
          id: 58330,
          title: "NASA Extends BEAM's Time on ISS",
          type: "Link",
          description: null,
          externalUrl:
            "https://www.nasa.gov/feature/nasa-extends-beam-s-time-on-the-international-space-station",
          publishedBy: null,
          publishedDate: null,
          files: [],
        },
        {
          id: 58323,
          title: "Success Story AES BEAM 2015-08-28",
          type: "Story",
          description: "<p>Success Story AES BEAM 2015-08-28</p> ",
          externalUrl: null,
          publishedBy: "",
          publishedDate: "Aug 2015",
          files: [
            {
              id: 39055,
              url: "https://techport.nasa.gov/file/39055",
              size: 368463,
            },
          ],
        },
        {
          id: 58325,
          title: "Success Story: Bigelow Expandable Activity Module (BEAM)",
          type: "Document",
          description: null,
          externalUrl: null,
          publishedBy: "",
          publishedDate: "Dec 2016",
          files: [
            {
              id: 39057,
              url: "https://techport.nasa.gov/file/39057",
              size: 215513,
            },
          ],
        },
      ],
      closeoutSummary: "<p>This project is ongoing.</p> ",
      closeoutDocuments: [],
      supportingOrganizations: [
        {
          name: "ATA Engineering, Inc.",
          type: "Industry",
          acronym: null,
          city: "San Diego",
          state: "CA",
          country: "United States",
        },
        {
          name: "Bigelow Aerospace",
          type: "Industry",
          acronym: "BA",
          city: null,
          state: null,
          country: null,
        },
        {
          name: "Boeing",
          type: "Industry",
          acronym: null,
          city: "Chicago",
          state: "IL",
          country: "United States",
        },
        {
          name: "Jacobs",
          type: "Industry",
          acronym: null,
          city: null,
          state: null,
          country: null,
        },
        {
          name: "Jet Propulsion Laboratory",
          type: "NASA Center",
          acronym: "JPL",
          city: "Pasadena",
          state: "CA",
          country: "United States",
        },
        {
          name: "Langley Research Center",
          type: "NASA Center",
          acronym: "LaRC",
          city: "Hampton",
          state: "VA",
          country: "United States",
        },
        {
          name: "NASA Headquarters",
          type: "NASA Center",
          acronym: "HQ",
          city: "Washington",
          state: "DC",
          country: "United States",
        },
        {
          name: "Sierra Nevada Corporation",
          type: "Industry",
          acronym: "SNC",
          city: "Sparks",
          state: "NV",
          country: "United States",
        },
        {
          name: "SpaceX",
          type: "Industry",
          acronym: null,
          city: null,
          state: null,
          country: null,
        },
        {
          name: "Wyle Laboratories, Inc.",
          type: "Industry",
          acronym: null,
          city: null,
          state: null,
          country: null,
        },
      ],
      coFundingPartners: [
        {
          name: "TASI",
          type: "International Organization",
          acronym: null,
          city: null,
          state: null,
          country: null,
        },
      ],
      primaryTas: [
        {
          id: 10854,
          code: "TX12",
          title: "Materials, Structures, Mechanical Systems, and Manufacturing",
          priority: null,
        },
      ],
      additionalTas: [
        {
          id: 10681,
          code: "TX06",
          title: "Human Health, Life Support, and Habitation Systems",
          priority: null,
        },
        {
          id: 10720,
          code: "TX07",
          title: "Exploration Destination Systems",
          priority: null,
        },
      ],
    },
  },
  {
    project: {
      id: 96438,
      lastUpdated: "2020-06-04",
      title: "FY18 IRTD Instrumentation Ring (IR) for Cryogenic Operations",
      status: "Completed",
      startDate: "Mar 2018",
      endDate: "Sep 2019",
      description:
        "<p>Cryogenic systems are required to store and transfer cryogenic commodities. Kennedy Space Center (KSC) ground operations (GO) are primarily involved with cryogenic systems that store and transfer liquid hydrogen (LH<sub>2</sub>) and liquid oxygen (LO<sub>2</sub>), and are used for propellant loading of launch vehicles. Propellant loading operations are complex activities. Operation and maintenance (O&M) of these cryogenic systems account for a sizeable portion of the life-cycle costs in any program.</p>  <p>At the present time, cryogenics systems at KSC incorporate many individual transducers and sensors (to measure pressure, temperature, flow, etc.) in and around the systems’ components (such as tanks, pumps, radiators, etc.) and along the connecting transfer pipes. These sensors are used to command, monitor and control the flow of cryogenics while maintaining the required conditions of the propellants.  These sensors and transducers are monitored by LH<sub>2</sub>/LOX system engineers, console operators, and subject matter experts (SME) to determine loading operations modes and the quality of flow along the system during transfer operations, among other things.</p>  <p>Several inefficiencies are identified with present approach. Among them are (a) the number of sensors utilized by the systems (not necessary optimized for sensor placement and coverage, primarily located around main components such tanks and pumps), (b) the number of individual penetrations and welds (required to house these sensors) with the potential for thermal and propellant leaks, (c) the number of associated power and signal cables to these sensors, (d) the inability to accurately determine in real time the quality of flow (by-phase, gas, liquid) across the system (which translate in longer loading activities), (d) the labor-intensive activities associated with operations and maintenance (O&M) of these systems (such as sensors’ remove and replace (R&R), calibration of sensors, system retesting, etc.)</p>  <p>The primary objective of the Cryogenic Instrumentation Ring (CIR) is to improve the monitoring and control capabilities of cryogenic loading operations when compared to traditional approaches. The CIR Improvement objectives are to: </p>  <ul><li>Optimize the number of required sensors and their locations across the cryogenic systems, which in turn \t<ul><li>Minimizes the number of penetrations and welds required for sensors</li><li>Reduces the associated power and signal cabling required</li><li>Reduces the amount of calibration, R&R activities, re-testing, etc.</li><li>Reduces the number of potential propellant leaks in the system</li></ul> \t</li><li>Improve the understanding of cryogenics flow throughout the system \t<ul><li>CIR units at specific locations of the system together with a real-time physics-based simulation of the system provides a holistic view of the overall process versus a fragmented series of partial assessments (tank, pumps, transfer lines, etc.) which in turn \t\t<ul><li>Reduces/Optimizes propellant usage during the different modes of the loading operation</li><li>Support real-time decision making and contingency actions if needed  </li></ul> \t\t</li></ul> \t</li><li>Improve instrumentation and process health management activities</li><li>Overall, reduce the O&M costs associated with these systems</li></ul>  <p> </p>  <p>The CIR approach seeks to demonstrate the benefits and feasibility of a localized instrumentation scheme that provides improved understanding of the cryogenics flow dynamics by measuring constituents at specified locations throughout the cryogenic system.  By positioning these CIR units between adjoining sections of cryogenic pipes (such in ), it reduces the number of penetrations required throughout the length of the pipe. </p>  <p>The CIR system could incorporate various sensing elements to measure temperature, pressure, flow rate, density, humidity, vacuum, oxygen, hydrogen, and helium concentrations among other parameters.  Other desired parameters may either be derived from these fundamental parameters (by sensor fusion) or quantified by a hybrid instrumentation approach (such as flow quality, two-phase flow regime determination, liquid level, etc.) </p>  <p> </p>  <p>The CIR concept was previously investigated under the Autonomous Cryogenics Loading Operation (ACLO) project, funded by the Space Technology Mission Directorate (STMD), Game Changing Development (GCD) program. CIR was one in a series of intelligent instrumentation concepts designed to support autonomy through the use of intelligent sensors and actuators, sensor fusion, and embedded health management capabilities in cryogenic operations. Under the ACLO approach, CIR units located at specific points (interfaces) of a cryogenic system would supports the evaluation of flow performance and system/components health, among other things.</p>  <p>The ACLO project combined a real-time high-fidelity physics based model of the targeted cryogenic system with real-time information obtained from the sensors in the system to assess and determine the optimal loading of cryogenics. CIR units would provide real-time snapshots (views) of the flow along the system at predetermined locations to determine the evolution over time of flow regimes and heat flow characteristics.  Integrating and fusing the data received from each CIR with the physics based model provides a complete and in-depth understanding of the performance and condition of the system.</p>  <p>Due to budget limitations, the ACLO project was cancelled when the CIR task was in the formulation phase.  This IR&TD project continues the development of the CIR concept, algorithms, and it prototypes a sample of instrumentation ring as proof of concept.</p> ",
      benefits:
        "<ul><li>Optimize the number of required sensors and their locations across the cryogenic systems, which in turn \t<ul><li>Minimizes the number of penetrations and welds required for sensors</li><li>Reduces the associated power and signal cabling required</li><li>Reduces the amount of calibration, R&R activities, re-testing, etc.</li><li>Reduces the number of potential propellant leaks in the system</li></ul> \t</li><li>Improve the understanding of cryogenics flow throughout the system \t<ul><li>CIR units at specific locations of the system together with a real-time physics-based simulation of the system provides a holistic view of the overall process versus a fragmented series of partial assessments (tank, pumps, transfer lines, etc.) which in turn \t\t<ul><li>Reduces/Optimizes propellant usage during the different modes of the loading operation</li><li>Support real-time decision making and contingency actions if needed  </li></ul> \t\t</li></ul> \t</li><li>Improve instrumentation and process health management activities</li><li>Overall, reduce the O&M costs associated with these systems</li></ul> ",
      technologyMaturityStart: "3",
      technologyMaturityCurrent: "4",
      technologyMaturityEnd: "5",
      destinations: ["Foundational Knowledge"],
      responsibleProgram: "Center Independent Research & Development: KSC IRAD",
      responsibleMissionDirectorateOrOffice: "Mission Support Directorate",
      leadOrganization: {
        name: "Kennedy Space Center",
        type: "NASA Center",
        acronym: "KSC",
        city: "Kennedy Space Center",
        state: "FL",
        country: "United States",
      },
      workLocations: ["Florida"],
      programManagers: ["Barbara L Brown"],
      principalInvestigators: ["Jose M Perotti"],
      website: "",
      libraryItems: [],
      closeoutSummary:
        "<p>Cryogenic systems are required to store and transfer cryogenic commodities. Kennedy Space Center (KSC) ground operations (GO) are primarily involved with cryogenic systems that store and transfer liquid hydrogen (LH<sub>2</sub>) and liquid oxygen (LO<sub>2</sub>), and are used for propellant loading of launch vehicles. Propellant loading operations are complex activities. Operation and maintenance (O&M) of these cryogenic systems account for a sizeable portion of the life-cycle costs in any program.</p>  <p>At the present time, cryogenics systems at KSC incorporate many individual transducers and sensors (to measure pressure, temperature, flow, etc.) in and around the systems’ components (such as tanks, pumps, radiators, etc.) and along the connecting transfer pipes. These sensors are used to command, monitor and control the flow of cryogenics while maintaining the required conditions of the propellants.  These sensors and transducers are monitored by LH<sub>2</sub>/LOX system engineers, console operators, and subject matter experts (SME) to determine loading operations modes and the quality of flow along the system during transfer operations, among other things.</p>  <p>Several inefficiencies are identified with present approach. Among them are (a) the number of sensors utilized by the systems (not necessary optimized for sensor placement and coverage, primarily located around main components such tanks and pumps), (b) the number of individual penetrations and welds (required to house these sensors) with the potential for thermal and propellant leaks, (c) the number of associated power and signal cables to these sensors, (d) the inability to accurately determine in real time the quality of flow (by-phase, gas, liquid) across the system (which translate in longer loading activities), (d) the labor-intensive activities associated with operations and maintenance (O&M) of these systems (such as sensors’ remove and replace (R&R), calibration of sensors, system retesting, etc.)</p>  <p>The primary objective of the Cryogenic Instrumentation Ring (CIR) is to improve the monitoring and control capabilities of cryogenic loading operations when compared to traditional approaches. The CIR Improvement objectives are to: </p>  <ul><li>Optimize the number of required sensors and their locations across the cryogenic systems, which in turn \t<ul><li>Minimizes the number of penetrations and welds required for sensors</li><li>Reduces the associated power and signal cabling required</li><li>Reduces the amount of calibration, R&R activities, re-testing, etc.</li><li>Reduces the number of potential propellant leaks in the system</li></ul> \t</li><li>Improve the understanding of cryogenics flow throughout the system \t<ul><li>CIR units at specific locations of the system together with a real-time physics-based simulation of the system provides a holistic view of the overall process versus a fragmented series of partial assessments (tank, pumps, transfer lines, etc.) which in turn \t\t<ul><li>Reduces/Optimizes propellant usage during the different modes of the loading operation</li><li>Support real-time decision making and contingency actions if needed  </li></ul> \t\t</li></ul> \t</li><li>Improve instrumentation and process health management activities</li><li>Overall, reduce the O&M costs associated with these systems</li></ul>  <p> </p>  <p>The CIR approach seeks to demonstrate the benefits and feasibility of a localized instrumentation scheme that provides improved understanding of the cryogenics flow dynamics by measuring constituents at specified locations throughout the cryogenic system.  By positioning these CIR units between adjoining sections of cryogenic pipes (such in ), it reduces the number of penetrations required throughout the length of the pipe. </p>  <p>The CIR system could incorporate various sensing elements to measure temperature, pressure, flow rate, density, humidity, vacuum, oxygen, hydrogen, and helium concentrations among other parameters.  Other desired parameters may either be derived from these fundamental parameters (by sensor fusion) or quantified by a hybrid instrumentation approach (such as flow quality, two-phase flow regime determination, liquid level, etc.) </p>  <p> </p>  <p>The CIR concept was previously investigated under the Autonomous Cryogenics Loading Operation (ACLO) project, funded by the Space Technology Mission Directorate (STMD), Game Changing Development (GCD) program. CIR was one in a series of intelligent instrumentation concepts designed to support autonomy through the use of intelligent sensors and actuators, sensor fusion, and embedded health management capabilities in cryogenic operations. Under the ACLO approach, CIR units located at specific points (interfaces) of a cryogenic system would supports the evaluation of flow performance and system/components health, among other things.</p>  <p>The ACLO project combined a real-time high-fidelity physics based model of the targeted cryogenic system with real-time information obtained from the sensors in the system to assess and determine the optimal loading of cryogenics. CIR units would provide real-time snapshots (views) of the flow along the system at predetermined locations to determine the evolution over time of flow regimes and heat flow characteristics.  Integrating and fusing the data received from each CIR with the physics based model provides a complete and in-depth understanding of the performance and condition of the system.</p>  <p>Due to budget limitations, the ACLO project was cancelled when the CIR task was in the formulation phase.  This IR&TD project continues the development of the CIR concept, algorithms, and it prototypes a sample of instrumentation ring as proof of concept.</p> ",
      closeoutDocuments: ["https://techport.nasa.gov/file/39595"],
      primaryTas: [
        {
          id: 10532,
          code: "TX01",
          title: "Propulsion Systems",
          priority: null,
        },
      ],
      additionalTas: [
        {
          id: 10681,
          code: "TX06",
          title: "Human Health, Life Support, and Habitation Systems",
          priority: null,
        },
        {
          id: 10807,
          code: "TX11",
          title: "Software, Modeling, Simulation, and Information Processing",
          priority: null,
        },
        {
          id: 10892,
          code: "TX13",
          title: "Ground, Test, and Surface Systems",
          priority: null,
        },
      ],
    },
  },
  {
    project: {
      id: 96439,
      lastUpdated: "2020-06-04",
      title:
        "FY18 IRTD Developing a Closed-loop, Bioregenerative Water Purification System for Future Planetary Habitats (Zero-G Anaerobic Membrane Bioreactor)",
      acronym: "ZA-AnMBR",
      status: "Completed",
      startDate: "Mar 2018",
      endDate: "Dec 2019",
      description:
        "<p>This project worked to solve the critical needs of future space missions to establish planetary bases that require large volumes of water to support astronauts, food generating plants, and key infrastructure including science experiments and thermal cooling systems by combining water purification, wastewater management, and plant production into a closed-loop, bioregenerative wastewater purification system.  A wastewater treatment facility was designed that will (1) process all forms of wastewater – to include all sources of crew-generated waste; (2) fit within architecture designed for the International Space Station (ISS), Gateway, and future Lunar Surface System habitats; and (3) be fully closed-loop requiring no chemical or filter resupply. Trade studies were performed to identify and characterize the input waste streams into the system, the functions required to perform treatment, and the output streams required by end-users. The required processing functions led to the creation of a system architecture though the downselection of optimal processing methods.</p>  <p>The initial subsystem, the Anaerobic Membrane BioReactor (AnMBR), was designed and built at the University of South Florida (USF) to process high concentration blackwater. The AnMBR subsystem breaks down particulate organic matter and large molecules through an anaerobic microbial membrane process. Prototype fabrication of AnMBR was performed under an NSSC contract utilizing USF lab capabilities, including machining and tooling resources with select components made in the USF 3D fabrication lab. The completed AnMBR system was designed to fit into the EXpedite the PRocessing of Experiments to the Space Station (EXPRESS) rack aboard the ISS. The EXPRESS rack design can potentially be used aboard a future microgravity flight or tweaked to fit within the Gateway Habitat element.</p>  <p>A Phototrophic Membrane Bioreactor (PMBR) was proposed as the secondary subsystem for the overall ‘closed-loop water purification’ system. The PMBR converts fertilizer compounds from wastewater to algal biomass, providing a source of oxygen, and sink for carbon dioxide. The systems primary goal was to produce a PMBR effluent stream that is suitable for higher order plant growth; this required a reduction of ammonia concentration. Using algae's oxygen production capabilities, the system converted some of the ammonia to nitrate with nitrifying bacteria. In addition to the effluent water stream used for plant growth, the PMBR also produced oxygen and sequesters carbon dioxide. This is currently being measured to quantify the impact of such a system on crew life support and future habitat development. In addition to collecting data on long-term testing, additional investigations are ongoing to further optimize the PMBR.</p>  <p>Future tasks and deliverables are expected under six-year project plan under an Advanced Exploration Systems funded proposal.</p> ",
      benefits:
        "<p>A wastewater treatment facility was designed that will (1) process all forms of wastewater – to include all sources of crew-generated waste; (2) fit within architecture designed for the International Space Station (ISS), Gateway, and future Lunar Surface System habitats; and (3) be fully closed-loop requiring no chemical or filter resupply.</p> ",
      technologyMaturityStart: "2",
      technologyMaturityCurrent: "3",
      technologyMaturityEnd: "3",
      destinations: ["Foundational Knowledge"],
      responsibleProgram: "Center Independent Research & Development: KSC IRAD",
      responsibleMissionDirectorateOrOffice: "Mission Support Directorate",
      leadOrganization: {
        name: "Kennedy Space Center",
        type: "NASA Center",
        acronym: "KSC",
        city: "Kennedy Space Center",
        state: "FL",
        country: "United States",
      },
      workLocations: ["Florida"],
      programManagers: ["Barbara L Brown"],
      principalInvestigators: ["Luke B Roberson", "Melanie T Pickett"],
      coInvestigators: ["Daniel Yeh", "Talon Bullard"],
      website: "",
      libraryItems: [],
      closeoutSummary:
        "<p>This project worked to solve the critical needs of future space missions to establish planetary bases that require large volumes of water to support astronauts, food generating plants, and key infrastructure including science experiments and thermal cooling systems by combining water purification, wastewater management, and plant production into a closed-loop, bioregenerative wastewater purification system.  A wastewater treatment facility was designed that will (1) process all forms of wastewater – to include all sources of crew-generated waste; (2) fit within architecture designed for the International Space Station (ISS), Gateway, and future Lunar Surface System habitats; and (3) be fully closed-loop requiring no chemical or filter resupply. Trade studies were performed to identify and characterize the input waste streams into the system, the functions required to perform treatment, and the output streams required by end-users. The required processing functions led to the creation of a system architecture though the downselection of optimal processing methods.</p>  <p>The initial subsystem, the Anaerobic Membrane BioReactor (AnMBR), was designed and built at the University of South Florida (USF) to process high concentration blackwater. The AnMBR subsystem breaks down particulate organic matter and large molecules through an anaerobic microbial membrane process. Prototype fabrication of AnMBR was performed under an NSSC contract utilizing USF lab capabilities, including machining and tooling resources with select components made in the USF 3D fabrication lab. The completed AnMBR system was designed to fit into the EXpedite the PRocessing of Experiments to the Space Station (EXPRESS) rack aboard the ISS. The EXPRESS rack design can potentially be used aboard a future microgravity flight or tweaked to fit within the Gateway Habitat element.</p>  <p>A Phototrophic Membrane Bioreactor (PMBR) was proposed as the secondary subsystem for the overall ‘closed-loop water purification’ system. The PMBR converts fertilizer compounds from wastewater to algal biomass, providing a source of oxygen, and sink for carbon dioxide. The systems primary goal was to produce a PMBR effluent stream that is suitable for higher order plant growth; this required a reduction of ammonia concentration. Using algae’s oxygen production capabilities, the system converted some of the ammonia to nitrate with nitrifying bacteria. In addition to the effluent water stream used for plant growth, the PMBR also produced oxygen and sequesters carbon dioxide. This is currently being measured to quantify the impact of such a system on crew life support and future habitat development. In addition to collecting data on long-term testing, additional investigations are ongoing to further optimize the PMBR.</p>  <p>Future tasks and deliverables are expected under six-year project plan under an Advanced Exploration Systems funded proposal.</p> ",
      closeoutDocuments: ["https://techport.nasa.gov/file/39596"],
      supportingOrganizations: [
        {
          name: "Kennedy Space Center",
          type: "NASA Center",
          acronym: "KSC",
          city: "Kennedy Space Center",
          state: "FL",
          country: "United States",
        },
      ],
      coFundingPartners: [
        {
          name: "University of South Florida",
          type: "Academic",
          acronym: "USF",
          city: "Tampa",
          state: "FL",
          country: "United States",
        },
      ],
      primaryTas: [
        {
          id: 10681,
          code: "TX06",
          title: "Human Health, Life Support, and Habitation Systems",
          priority: null,
        },
      ],
      additionalTas: [],
    },
  },
  {
    project: {
      id: 94205,
      lastUpdated: "2020-06-02",
      title:
        "Miniaturized Scrubber System for Long Duration Exploration andHabitation Applications",
      acronym: "MSS",
      status: "Active",
      startDate: "Aug 2015",
      endDate: "Dec 2021",
      description:
        "<p>The aim of this effort is to develop a minaturized carbon dioxide scrubber system based on proprietary Dynetics technology to provide atmosphere revitalization.  The system will operate with low to no consumable requirements, minimal maintenance, and supports existing oxygen recovery processes. An endurance ground tests will be performed to inform a flight experiment in the 2020 timeframe.  This activity is a NextSTEP partnership between NASA and Dynetics.</p> ",
      benefits:
        "<p>Perform highly reliable, continuous carbon dioxide scrubbing in spacecraft.  In-atmosphere water molecules are preserved.  Current systems require consumable resupply and substantial maintenance, consume more power and occupy more space than desired.  The MSS project will develop a miniaturized system designed for infrequent maintenance that requires minimal astronaut interaction.  The system minimizes consumables, size weight and power while maximizing carbon dioxide removal.</p> ",
      technologyMaturityStart: "3",
      technologyMaturityCurrent: "3",
      technologyMaturityEnd: "6",
      destinations: ["The Moon"],
      supportedMissionType: "Planned Mission (Pull)",
      responsibleProgram: "Advanced Exploration Systems Division",
      responsibleMissionDirectorateOrOffice:
        "Human Exploration and Operations Mission Directorate",
      leadOrganization: {
        name: "Dynetics, Inc.",
        type: "Industry",
        acronym: null,
        city: "Huntsville",
        state: "AL",
        country: "United States",
      },
      workLocations: ["Alabama", "District of Columbia", "Maryland", "Texas"],
      programDirectors: ["Christopher L Moore"],
      projectManagers: ["Marlon R Cox", "Morgan B Abney", "Jimmy Allen"],
      principalInvestigators: ["Jimmy Allen", "Jason Pohly"],
      coInvestigators: ["Ryan Hooper", "Eric Tuck"],
      website: "",
      libraryItems: [
        {
          id: 59031,
          title: "Dynetics Miniaturized Scrubber System Concept",
          type: "Image",
          description:
            "This image shows a notional concept of the DyneticsMiniaturizedScrubber. System.",
          externalUrl: null,
          publishedBy: null,
          publishedDate: null,
          files: [
            {
              id: 39656,
              url: "https://techport.nasa.gov/file/39656",
              size: 340310,
            },
          ],
        },
      ],
      closeoutSummary: "",
      closeoutDocuments: [],
      supportingOrganizations: [
        {
          name: "Jet Propulsion Laboratory",
          type: "NASA Center",
          acronym: "JPL",
          city: "Pasadena",
          state: "CA",
          country: "United States",
        },
        {
          name: "Johnson Space Center",
          type: "NASA Center",
          acronym: "JSC",
          city: "Houston",
          state: "TX",
          country: "United States",
        },
        {
          name: "Kitty Hawk",
          type: "Industry",
          acronym: null,
          city: "",
          state: "",
          country: null,
        },
        {
          name: "Marshall Space Flight Center",
          type: "NASA Center",
          acronym: "MSFC",
          city: "Huntsville",
          state: "AL",
          country: "United States",
        },
        {
          name: "NASA Headquarters",
          type: "NASA Center",
          acronym: "HQ",
          city: "Washington",
          state: "DC",
          country: "United States",
        },
        {
          name: "The University of Alabama",
          type: "Academic",
          acronym: null,
          city: "Huntsville",
          state: "AL",
          country: "United States",
        },
      ],
      coFundingPartners: [
        {
          name: "Dynetics, Inc.",
          type: "Industry",
          acronym: null,
          city: "Huntsville",
          state: "AL",
          country: "United States",
        },
      ],
      primaryTas: [
        {
          id: 10681,
          code: "TX06",
          title: "Human Health, Life Support, and Habitation Systems",
          priority: null,
        },
        {
          id: 10682,
          code: "TX06.1",
          title:
            "Environmental Control & Life Support Systems (ECLSS) and Habitation Systems",
          priority: null,
        },
        {
          id: 10683,
          code: "TX06.1.1",
          title: "Atmosphere Revitalization",
          priority: null,
        },
      ],
      additionalTas: [],
    },
  },
  {
    project: {
      id: 94183,
      lastUpdated: "2020-06-02",
      title:
        "NextSTEP Phase 2 Environmental Control Life Support Systems Modularity Study",
      acronym: "NSTEP ECLSS",
      status: "Active",
      startDate: "Aug 2015",
      endDate: "Mar 2021",
      description:
        "<p>The objectives of the Environmental Control and Life Support Systems (ECLSS) Modularity Phase 2 study are to add activities that are needed to evolve ECLSS from supporting an initial cislunar habitat toward a habitat for deep space travel.  This program will develop an ECLSS architecture for a cislunar habitat that is evolvable to support closed-loop, earth independent, deep space exploration applications; generate a dynamic modular ECLSS model; develop a fully functional prototype of the selected control architecture; support the development of ECLSS Standards and Interfaces; leverage the state-of-the-art intelligent technologies to enhance ECLSS performance, safety and reliability; develop and fabricate a series of demonstration pallets; and develop and fabricate an Air Revitalization System (ARS) Prototype.</p> ",
      benefits:
        "<p>This NextSTEP Phase 2 partnership with Collins Aerospace Systems will continue to evolve the ECLSS needed for a habitat in cislunar space that can be used to support missions to Moon and deep space.</p> ",
      technologyMaturityStart: "3",
      technologyMaturityCurrent: "3",
      technologyMaturityEnd: "5",
      destinations: ["Mars"],
      supportedMissionType: "Planned Mission (Pull)",
      responsibleProgram: "Advanced Exploration Systems Division",
      responsibleMissionDirectorateOrOffice:
        "Human Exploration and Operations Mission Directorate",
      leadOrganization: {
        name: "NASA Headquarters",
        type: "NASA Center",
        acronym: "HQ",
        city: "Washington",
        state: "DC",
        country: "United States",
      },
      workLocations: [
        "Alabama",
        "California",
        "Connecticut",
        "Massachusetts",
        "New York",
      ],
      programDirectors: ["Christopher L Moore"],
      projectManagers: ["Marlon R Cox"],
      principalInvestigators: [
        "Walter F Schneider",
        "Daniel J Barta",
        "Mark Jernigan",
      ],
      coInvestigators: ["Jay L Perry", "Daniel J Barta", "Miriam J Sargusingh"],
      website: "https://www.nasa.gov/nextstep",
      libraryItems: [],
      closeoutSummary: "",
      closeoutDocuments: [],
      supportingOrganizations: [
        {
          name: "Jet Propulsion Laboratory",
          type: "NASA Center",
          acronym: "JPL",
          city: "Pasadena",
          state: "CA",
          country: "United States",
        },
        {
          name: "Johnson Space Center",
          type: "NASA Center",
          acronym: "JSC",
          city: "Houston",
          state: "TX",
          country: "United States",
        },
        {
          name: "Marshall Space Flight Center",
          type: "NASA Center",
          acronym: "MSFC",
          city: "Huntsville",
          state: "AL",
          country: "United States",
        },
        {
          name: "UTC Aerospace Systems",
          type: "Industry",
          acronym: "UTAS",
          city: null,
          state: "CT",
          country: "United States",
        },
      ],
      primaryTas: [
        {
          id: 10681,
          code: "TX06",
          title: "Human Health, Life Support, and Habitation Systems",
          priority: null,
        },
        {
          id: 10682,
          code: "TX06.1",
          title:
            "Environmental Control & Life Support Systems (ECLSS) and Habitation Systems",
          priority: null,
        },
        {
          id: 10683,
          code: "TX06.1.1",
          title: "Atmosphere Revitalization",
          priority: null,
        },
      ],
      additionalTas: [],
    },
  },
  {
    project: {
      id: 94884,
      lastUpdated: "2020-06-01",
      title: "NASA Platform for Autonomous Systems",
      acronym: "NPAS",
      status: "Active",
      startDate: "Sep 2016",
      endDate: "Oct 2020",
      description:
        "<p>Autonomous operations are critical for the success, safety and crew survival of NASA deep space missions beyond low Earth orbit, including Gateway. For the past 10 years, Stennis Space Center (SSC) has been developing, and has demonstrated an innovative software platform, along with expertise and processes for implementation of autonomous operations.</p>  <p>The current version is called NASA Platform for Autonomous Systems (NPAS).  NPAS is developed using the G2 platform - a COTS product (a MIT derivative). NPAS provides the foundational technology and processes to evolve from traditional “Brute-Force Autonomy” (BFA) towards innovative “Thinking Autonomy” (TA).  NPAS applications encompass comprehensive SysML-like live-models that permit model-based real-time analysis and operations. NPAS uniquely extends the paradigm of model-based systems engineering (MBSE) beyond static models, into live models for real-time thinking autonomous operations that can be rapidly and affordably implemented, deployed, re-used and evolved.</p>  <p>NPAS supports the concept that achieving autonomous operations, beyond developing algorithms for dealing with specific cases that warrant an autonomous response (or reaction), must address implementing strategies for autonomy that are guided by combination of requirements that include, policy, operations procedures, mission objectives.  In this context, an autonomous system makes the best use of available resources to achieve the specified mission.</p>  <p>NPAS uniquely addresses autonomous operation requirements and integrates primary functionalities including: (1) autonomy strategies based on concepts of operation, while taking advantage of system attributes such as redundancy, persistence strategies such as repeating commands, and others; (2) Integrated System Health Management (ISHM) strategies, for anomaly detection, diagnostics and effects (FMEA), prognostics, and comprehensive awareness; (3) object libraries and infrastructure to create knowledge models of applications (reusable);  (4) infrastructure to create mission operations encompassing plans, schedules, and sequences; and (5) infrastructure to develop user interfaces providing comprehensive awareness for users, developers, and management</p>  <p>A goal of the current NPAS project is to integrate with other Advanced Exploration Systems (AES)/HEOMD projects at Johnson Space Center's (JSC's) Integrated Power Avionics and Software (iPAS) “habitat” test article. NPAS was used to demonstrate integration with the Autonomous Power Controller (APC) associated with the AES Modular Power System. The demonstration included successful nominal and fault conversations between the APC and the NPAS Vehicle System Manager (VSM). The VSM application ran from a networked single-board computer housed in iPAS.</p>  <p>Additionally, NPAS provided an autonomous operational capability that was integrated into a space habitation module “mock-up” built by a partner that was awarded a NASA Next Space Technologies for Exploration Partnerships-2 (NextSTEP-2) demonstration activity. NPAS was used to create an autonomous operations habitat module application encompassing a Vehicle Manger (VehMgr) and an autonomous Electrical Power System (EPS) that powers the habitat. These NPAS applications were architected to demonstrate hierarchical distributed autonomous capability and were integrated into the existing habitation “mock-up” architecture and UI. The NPAS VehMgr UI provided awareness and information on activities associated with near rectilinear halo orbit – NRHO (orbit proposed for Gateway).  For the demonstration, the VehMgr UI provided access to the following information:</p>  <ul><li>Vehicle Timeline Display: showing activity timeline for the habitat and its systems (e.g. electrical power system) \t<ul><li>Activities displayed in the timeline showed what was happening at the current time, and activities 5 hours before and after current time</li></ul> \t</li><li>Modes of operation of the habitat:  e.g. Station Keeping, crewed/uncrewed</li><li>Health of the habitat: i.e. nominal, degraded, faulted, recover, safed, failed, standby, test, off</li><li>Alerts:  a placeholder due to the fact that the habitat was notionally fixed to nominal for the Habitation in the Life (HITL) demonstration</li><li>Time:  local and ground</li><li>Command Authority State:  autonomous, ground, or crew</li><li>Persistent high level “quick look” awareness about the systems in the habitat (i.e. EPS, Life Support System, Communications, Thermal, Mechanical, Guidance Navigation & Control-GNC, and Avionics) such as the health of each system, and operational state</li><li>In-depth awareness about the EPS system with one mouse click (e.g. life schematic awareness showing visual flow of power to loads, battery state and availability, solar array and regulator); this was done for the Electrical Power System, with telemetry fed by a simulation to the NPAS autonomous application model \t<ul><li>The UI is designed so that this in-depth awareness can be implemented for each system in the habitat</li></ul> \t</li></ul>  <p>NPAS applications  integrated with the simulation environment (prototype Flight Software-FSW-using Core Flight System (CFS) running on VxWorks-653 2.4), including telemetry coming from a simulator; operating under basic Concepts of Operation (e.g. nominal operation, crewed); communicating via the CFS Software Bus Network (SBN).</p>  <p>NPAS VehMGR and NPAS EPS were included as part of the final deliverable to NASA by the NextStep-2 partner. NPAS autonomy implementation was included in the evaluation by NASA, as part of HITL, which encompassed three 8-hour days of simulated habitat operations executed by astronauts that included interaction with the NPAS autonomous operations (NPAS VehMgr and NPAS EPS). The evaluation also included non-crew expert personnel.</p>  <p>For these projects, the NPAS, and corresponding engineering processes, rapidly achieved implementation of intelligent distributed autonomy encompassing a capability that is consistent with the  current concepts of operations associated with Gateway, including tools for  implementation of a reference architecture that includes Vehicle System Manager, Module Manager, system, subsystem down to component level autonomy,  validating NPAS as an efficient, cost-effective, integrated, and unique autonomous operation software capability.</p>  <p>Currently, NPAS includes autonomy strategies, ISHM strategies and libraries of system elements for electrical, mechanical, computer, and communications applications that can be used for a wide range of implementations.</p>  <p>NPAS represents an innovative approach and technology to rapidly implement and deploy intelligent/thinking autonomous operations. NPAS encompasses tools for creating an integrated autonomy solution: comprehensive (real-time) operational knowledge models (beyond the comprehensiveness of SysML models) –capturing digital twin/digital thread information, health assessment, diagnostics, anomaly detection (FMEA), autonomous operational strategies, mission plan scheduling and execution.</p> ",
      benefits:
        "<p>NPAS software is being cultivated as a paradigm shift in the way NASA develops autonomous operation software that will enable cost effective, comprehensive, “thinking”, and evolutionary autonomy for future space and ground systems.</p>  <p>NPAS has reusable core capabilities</p>  <ul><li>Leverageable – system elements and modelling code applies to a wide range of system applications (reusable)  </li><li>Sustainable (modular, knowledge-base that enables systematic changes, inherent integration that is maintained throughout the life cycle of NPAS applications).</li><li>Scalable within each autonomous application and across networked distributed autonomous applications</li><li>affordable – long term cost savings</li><li>reduced delivery time</li><li>evolvable – enables systematic augmentation of knowledge and autonomy capability</li></ul>  <p>NPAS has cross-cutting relevance for autonomy across multiple applications, including ground test and launch systems, space systems, satellite systems, Deep Space Network, aeronautics, and science. NPAS software developers are targeting NPAS implementation processes to meet NASA Advanced Exploration System's (AES's) current avionics architecture requirements for Gateway, and space habitat modules; and continue to provide benefit to commercial space industry partners.</p>  <p> </p>  <p> </p>  <p> </p> ",
      technologyMaturityStart: "5",
      technologyMaturityCurrent: "7",
      technologyMaturityEnd: "9",
      destinations: ["Earth", "The Moon", "Mars"],
      supportedMissionType: "Planned Mission (Pull)",
      responsibleProgram: "Advanced Exploration Systems Division",
      responsibleMissionDirectorateOrOffice:
        "Human Exploration and Operations Mission Directorate",
      leadOrganization: {
        name: "Stennis Space Center",
        type: "NASA Center",
        acronym: "SSC",
        city: "Stennis Space Center",
        state: "MS",
        country: "United States",
      },
      workLocations: ["California", "Mississippi", "Ohio", "Texas"],
      programDirectors: ["Christopher L Moore"],
      projectManagers: ["Lauren W Underwood"],
      principalInvestigators: ["Fernando Figueroa", "Aaron P Head"],
      coInvestigators: ["Mark Walker", "Jonathan A Morris"],
      website:
        "https://technology.ssc.nasa.gov/techdev/autonomous-systems/npas.asp",
      libraryItems: [
        {
          id: 52956,
          title: "Autonomous Systems Lab",
          type: "Image",
          description: "SSC Autonomous Systems Lab",
          externalUrl: null,
          publishedBy: null,
          publishedDate: null,
          files: [
            {
              id: 37948,
              url: "https://techport.nasa.gov/file/37948",
              size: 5459045,
            },
          ],
        },
        {
          id: 52959,
          title: "Integrated System Health Management (ISHM) and Autonomy",
          type: "Document",
          description: null,
          externalUrl: null,
          publishedBy: "SciTech 2018",
          publishedDate: "Jan 2018",
          files: [
            {
              id: 37951,
              url: "https://techport.nasa.gov/file/37951",
              size: 1312279,
            },
          ],
        },
        {
          id: 52963,
          title: "NASA Platform for Autonomous Systems",
          type: "Document",
          description: null,
          externalUrl: null,
          publishedBy: "AiAA SciTech 2019",
          publishedDate: "Jan 2019",
          files: [
            {
              id: 37955,
              url: "https://techport.nasa.gov/file/37955",
              size: 2223460,
            },
          ],
        },
        {
          id: 52962,
          title: "NPAS ",
          type: "Image",
          description: "NASA Platform for Autonomous Systems",
          externalUrl: null,
          publishedBy: null,
          publishedDate: null,
          files: [
            {
              id: 37954,
              url: "https://techport.nasa.gov/file/37954",
              size: 5327173,
            },
          ],
        },
        {
          id: 52958,
          title: "NPAS Functional Architecture",
          type: "Image",
          description: "NPAS functional architecture overview",
          externalUrl: null,
          publishedBy: null,
          publishedDate: null,
          files: [
            {
              id: 37950,
              url: "https://techport.nasa.gov/file/37950",
              size: 434770,
            },
          ],
        },
        {
          id: 52957,
          title: "NPAS Roadmap",
          type: "Image",
          description:
            "NPAS Roadmap - autonomous operation from ground to space applications",
          externalUrl: null,
          publishedBy: null,
          publishedDate: null,
          files: [
            {
              id: 37949,
              url: "https://techport.nasa.gov/file/37949",
              size: 1093323,
            },
          ],
        },
        {
          id: 52954,
          title: "SSC Autonomous Systems Lab",
          type: "Link",
          description: null,
          externalUrl:
            "https://technology.ssc.nasa.gov/techdev/autonomous-systems/autonomous-systems-lab.asp",
          publishedBy: null,
          publishedDate: null,
          files: [],
        },
        {
          id: 52955,
          title: "SSC Partnership - G2 for Spaceflight Computers",
          type: "Link",
          description: null,
          externalUrl:
            "https://technology.ssc.nasa.gov/techdev/autonomous-systems/autonomous-systems-lab.asp",
          publishedBy: null,
          publishedDate: null,
          files: [],
        },
      ],
      closeoutSummary: "",
      closeoutDocuments: [],
      supportingOrganizations: [
        {
          name: "Ames Research Center",
          type: "NASA Center",
          acronym: "ARC",
          city: "Moffett Field",
          state: "CA",
          country: "United States",
        },
        {
          name: "Glenn Research Center",
          type: "NASA Center",
          acronym: "GRC",
          city: "Cleveland",
          state: "OH",
          country: "United States",
        },
        {
          name: "Jet Propulsion Laboratory",
          type: "NASA Center",
          acronym: "JPL",
          city: "Pasadena",
          state: "CA",
          country: "United States",
        },
        {
          name: "Johnson Space Center",
          type: "NASA Center",
          acronym: "JSC",
          city: "Houston",
          state: "TX",
          country: "United States",
        },
      ],
      coFundingPartners: [
        {
          name: "Office of the Chief Technologist",
          type: "NASA Office",
          acronym: "OCT",
          city: null,
          state: null,
          country: null,
        },
        {
          name: "Space Technology Mission Directorate",
          type: "NASA Mission Directorate",
          acronym: "STMD",
          city: null,
          state: null,
          country: null,
        },
      ],
      primaryTas: [
        {
          id: 10779,
          code: "TX10",
          title: "Autonomous Systems",
          priority: null,
        },
        {
          id: 10795,
          code: "TX10.3",
          title: "Collaboration and Interaction",
          priority: null,
        },
        {
          id: 10798,
          code: "TX10.3.3",
          title: "Goal and Task Negotiation",
          priority: null,
        },
      ],
      additionalTas: [],
    },
  },
  {
    project: {
      id: 13543,
      lastUpdated: "2020-06-01",
      title: "Spacecraft Fire Safety Demonstration",
      acronym: "Saffire",
      status: "Active",
      startDate: "Oct 2011",
      endDate: "Dec 2020",
      description:
        "<p>The objective of the Spacecraft Fire Safety Demonstration project is to develop and conduct large-scale fire safety experiments on an International Space Station resupply vehicle after it leaves the ISS and before it re-enters the Earth's atmosphere. Three Spacecraft Fire Experiment (Saffire) flight units were developed and have flown on three sequential flights of Northrop Grumman's (formerly Orbital ATK) Cygnus re-supply vehicle. Saffire-I was launched on OA-6 in March 2016, Saffire-II on OA-5 in October 2016, and Saffire-III on OA-7 in March 2017.  The Saffire-I, II, and III experiments were all operated successfully in June 2016, November 2016, and June 2017, respectively.</p>  <p>Three more Saffire experiments, Saffire-IV-VI, are now being developed to continue to investigate material flammability risks that will be faced by the crew on NASA's long duration exploration missions, especially at reduced pressure and higher oxygen concentrations. These experiments will also obtain data on large-scale spacecraft fire detection, monitoring, and post-fire cleanup as well as obtain valuable data to allow spacecraft designers and engineers to predict the development of fire scenarios in exploration vehicles and habitats. The SFS Demo Project is managed by NASA John H. Glenn Research Center (GRC) who also developed the design and fabricated the hardware for Saffire-I-III. Saffire-IV-VI are being developed by a team comprised of personnel from NASA and ZIN Technologies, Inc.</p>  <p>Personnel from NASA Johnson Spaceflight Center, NASA Jet Propulsion Lab, and the NASA White Sands Test Facility also provided instruments and testing support for the Saffire experiments. The NASA team is augmented by an international topical team assembled by the European Space Agency (ESA). Each member of this team brings expertise and funding from their respective space and research agencies for their activities. The experiment hardware for Saffire-I-VI is approximately 53 cm x 90 cm x 133 cm and consists of a flow duct, containing the sample material to be burned, fans, and flow straightener, and an avionics bay, containing the power management system, control computer, signal conditioning card, and cameras. Saffire-I and III had a single large sample (0.4 m x 0.9 m) made of a composite fabric (75% cotton/25% fiberglass by mass) that has been studied in previous low-gravity experiments although using much smaller samples. This sample burned completely during the tests and yielded information about the fate (flame size and spread rate) of a large-scale fire in low-gravity. Saffire-II had nine samples (5-cm wide x 30-cm long) of various materials that were selected to investigate the low-gravity Maximum Oxygen Concentration (MOC) flammability limits in long-term low gravity. These samples emulate the configuration used in NASA-STD-6001 Test 1, the flammability test conducted in normal gravity to determine if a flame will spread upward over the sample or if it will self-extinguish. A material that self-extinguishes is considered as being safe for use in spacecraft from the standpoint of flammability.</p>  <p>To conduct the Saffire experiments, the Saffire hardware is loaded in the Cygnus Pressurized Cargo Module by Northrop Grumman and launched from the Wallops Flight Facility. Once at the International Space Station, Saffire remains unpowered on Cygnus while supplies for the ISS are off-loaded by the crew. Once supplies are off-loaded and replaced with trash, Cygnus departs. When the vehicle reaches a safe distance from the ISS, Saffire will be powered on by a team of Northrop Grumman and Saffire engineers working from Northrop Grumman's Dulles Control Center in Dulles, VA. After conducting system checks, Cygnus will be put into free drift and the experiment initiated. Saffire-I, II, and III ran autonomously for about 2-1/2 hours. With the expanded objectives of Saffire-IV-VI, the experiment will require about 8 hours to be completed. When the experiment is complete, Cygnus continues to orbit the earth while the data is downlinked to various ground stations. When downlink is complete, Cygnus will then begin its reentry into the Earth's atmosphere where it will burn up over the Pacific Ocean. The design for the Saffire-IV-VI experiments is complete and the units are being fabricated to be followed by extensive ground testing to verify operation. Saffire-IV is scheduled to be launched in October 2019, with Saffire-V and VI following in February and May of 2020.</p> ",
      benefits:
        "<p>This project will benefit all future human exploration missions by providing data and validated models that describe the growth of large-scale spacecraft fires. The project is also demonstrating the effectiveness of fire monitoring and response technologies planned for use on Orion and future spacecraft. The data, and the models validated using that data, will be used to developed effective fire safety strategies, equipment, and procedures for all crewed vehicles used on exploration missions.</p>  <p> </p> ",
      technologyMaturityStart: "3",
      technologyMaturityCurrent: "4",
      technologyMaturityEnd: "7",
      destinations: ["Earth"],
      supportedMissionType: "Planned Mission (Pull)",
      responsibleProgram: "Advanced Exploration Systems Division",
      responsibleMissionDirectorateOrOffice:
        "Human Exploration and Operations Mission Directorate",
      leadOrganization: {
        name: "Glenn Research Center",
        type: "NASA Center",
        acronym: "GRC",
        city: "Cleveland",
        state: "OH",
        country: "United States",
      },
      workLocations: [
        "Colorado",
        "District of Columbia",
        "New Mexico",
        "Virginia",
      ],
      programDirectors: ["Christopher L Moore"],
      projectManagers: ["Gary A Ruff"],
      principalInvestigators: ["David L Urban"],
      website: "",
      libraryItems: [
        {
          id: 50332,
          title:
            "Development of Large-Scale Spacecraft Fire Safety Experiments",
          type: "Story",
          description:
            "<p>This is paper was presented at the 43rd International Conference on Environmental Systems held on July 14-18, 2013 in Vail, CO. It describes the Spacecraft Fire Safety Demonstration (Saffire) project as well as the activities of the Spacecraft Fire Safety International Topical Team that support this experiment and other fire safety topics.</p> ",
          externalUrl: null,
          publishedBy: "American Institute of Aeronautics and Astronautics",
          publishedDate: "Jul 2013",
          files: [
            {
              id: 36728,
              url: "https://techport.nasa.gov/file/36728",
              size: 1628180,
            },
          ],
        },
        {
          id: 50339,
          title: "Flame spread: Effects of microgravity and scale",
          type: "Document",
          description: null,
          externalUrl: null,
          publishedBy: "Elsevier",
          publishedDate: "Jan 2019",
          files: [
            {
              id: 36733,
              url: "https://techport.nasa.gov/file/36733",
              size: 4185301,
            },
          ],
        },
        {
          id: 50338,
          title: "Results of Large-Scale Spacecraft Flammability Tests",
          type: "Story",
          description:
            "<p>This is paper was presented at the 47th International Conference on Environmental Systems held on July 16-20, 2017 in Charleston, South Carolina. It describes the Spacecraft Fire Safety Demonstration (Saffire) project and focuses on the results of the Saffire-I and Saffire-II experiments.</p> ",
          externalUrl: null,
          publishedBy: "International Conference on Environmental Systems",
          publishedDate: "Jul 2017",
          files: [],
        },
        {
          id: 50335,
          title:
            "Success Story: Development of the Spacecraft Fire Experiment (Saffire)",
          type: "Document",
          description: null,
          externalUrl: null,
          publishedBy: "",
          publishedDate: "Dec 2016",
          files: [
            {
              id: 36731,
              url: "https://techport.nasa.gov/file/36731",
              size: 176284,
            },
          ],
        },
        {
          id: 50333,
          title: "The Saffire Logo",
          type: "Image",
          description:
            "The Saffire logo shows the Cygnus vehicle in the foreground. The three bright stars to the left of the burning sapphire gem represent the three experiment units being developed.",
          externalUrl: null,
          publishedBy: null,
          publishedDate: null,
          files: [
            {
              id: 36729,
              url: "https://techport.nasa.gov/file/36729",
              size: 429460,
            },
          ],
        },
      ],
      closeoutSummary: "",
      closeoutDocuments: [],
      supportingOrganizations: [
        {
          name: "Case Western Reserve University",
          type: "Academic",
          acronym: null,
          city: "Cleveland",
          state: "OH",
          country: "United States",
        },
        {
          name: "Jet Propulsion Laboratory",
          type: "NASA Center",
          acronym: "JPL",
          city: "Pasadena",
          state: "CA",
          country: "United States",
        },
        {
          name: "Johnson Space Center",
          type: "NASA Center",
          acronym: "JSC",
          city: "Houston",
          state: "TX",
          country: "United States",
        },
        {
          name: "NASA Headquarters",
          type: "NASA Center",
          acronym: "HQ",
          city: "Washington",
          state: "DC",
          country: "United States",
        },
        {
          name: "Northrop Grumman Innovation Systems",
          type: "Industry",
          acronym: null,
          city: "Dulles",
          state: "VA",
          country: "United States",
        },
        {
          name: "TDA Research, Inc.",
          type: "Industry",
          acronym: null,
          city: "Wheat Ridge",
          state: "CO",
          country: "United States",
        },
        {
          name: "University of California at Berkeley",
          type: "Academic",
          acronym: null,
          city: "Berkeley",
          state: "CA",
          country: "United States",
        },
        {
          name: "Vista Photonics, Inc.",
          type: "Industry",
          acronym: null,
          city: "Santa Fe",
          state: "NM",
          country: "United States",
        },
        {
          name: "White Sands Test Facility",
          type: "NASA Facility",
          acronym: "WSTF",
          city: "Las Cruces",
          state: "NM",
          country: "United States",
        },
      ],
      coFundingPartners: [
        {
          name: "European Space Agency",
          type: "International Organization",
          acronym: null,
          city: null,
          state: null,
          country: null,
        },
      ],
      primaryTas: [
        {
          id: 10681,
          code: "TX06",
          title: "Human Health, Life Support, and Habitation Systems",
          priority: null,
        },
        {
          id: 10701,
          code: "TX06.4",
          title: "Environmental Monitoring, Safety, and Emergency Response",
          priority: null,
        },
        {
          id: 10703,
          code: "TX06.4.2",
          title: "Fire: Detection, Suppression, and Recovery",
          priority: null,
        },
      ],
      additionalTas: [],
    },
  },
  {
    project: {
      id: 94234,
      lastUpdated: "2020-05-29",
      title: "Accurate Strength & Life Prediction",
      status: "Completed",
      startDate: "Oct 2014",
      endDate: "Sep 2019",
      description:
        "<p>The Accurate Strength &amp; Life Prediction challenge develops validated strength and life prediction tools with known accuracy for complex composite structures and standardized procedures for their reliable use.</p>",
      benefits:
        "<p>This technical challenge addresses Verification and Validation methods for applications in strength and life prediction tools for complex composite structures and standardized procedures. The development of high fidelity analysis tools will enable reliable predictions of strength and life of composite structures with damage or defects, along with prediction of structure failures when subjected to high-energy impacts. This research supports the feasibility of manufacturing future aircraft in ultra-efficient but non-traditional configurations.</p>",
      technologyMaturityStart: "2",
      technologyMaturityCurrent: "3",
      technologyMaturityEnd: "4",
      destinations: ["Earth"],
      responsibleProgram: "Advanced Air Vehicles",
      responsibleMissionDirectorateOrOffice:
        "Aeronautics Research Mission Directorate",
      leadOrganization: {
        name: "Langley Research Center",
        type: "NASA Center",
        acronym: "LaRC",
        city: "Hampton",
        state: "VA",
        country: "United States",
      },
      workLocations: ["Ohio", "Virginia"],
      programDirectors: ["James Kenyon"],
      projectManagers: ["Richard D Young"],
      website: "https://www.nasa.gov/aeroresearch/programs/aavp/ac",
      libraryItems: [],
      closeoutSummary: "",
      closeoutDocuments: [],
      supportingOrganizations: [
        {
          name: "Arizona State University",
          type: "Academic",
          acronym: "ASU",
          city: "Tempe",
          state: "AZ",
          country: "United States",
        },
        {
          name: "Aurora",
          type: "Industry",
          acronym: null,
          city: null,
          state: null,
          country: null,
        },
        {
          name: "Boeing",
          type: "Industry",
          acronym: null,
          city: "Chicago",
          state: "IL",
          country: "United States",
        },
        {
          name: "Collier Research & Development Corporation",
          type: "Industry",
          acronym: null,
          city: "Hampton",
          state: "VA",
          country: "United States",
        },
        {
          name: "General Electric",
          type: "Industry",
          acronym: "GE",
          city: "Boston",
          state: "MA",
          country: "United States",
        },
        {
          name: "Glenn Research Center",
          type: "NASA Center",
          acronym: "GRC",
          city: "Cleveland",
          state: "OH",
          country: "United States",
        },
        {
          name: "Lockheed Martin",
          type: "Industry",
          acronym: null,
          city: "Palo Alto",
          state: "CA",
          country: "United States",
        },
        {
          name: "McNAIR",
          type: "Industry",
          acronym: null,
          city: null,
          state: null,
          country: null,
        },
        {
          name: "National Institute for Aviation Research",
          type: "Academic",
          acronym: null,
          city: null,
          state: null,
          country: null,
        },
        {
          name: "National Institute of Aerospace",
          type: "Industry",
          acronym: null,
          city: null,
          state: null,
          country: null,
        },
        {
          name: "Northrop Grumman Innovation Systems",
          type: "Industry",
          acronym: null,
          city: "Dulles",
          state: "VA",
          country: "United States",
        },
        {
          name: "United Technologies Corporation",
          type: "Industry",
          acronym: null,
          city: null,
          state: null,
          country: null,
        },
        {
          name: "University of California, San Diego",
          type: "Academic",
          acronym: null,
          city: "La Jolla",
          state: "CA",
          country: "United States",
        },
        {
          name: "University of Texas at Arlington",
          type: "Academic",
          acronym: null,
          city: "Arlington",
          state: "TX",
          country: "United States",
        },
      ],
      primaryTas: [
        {
          id: 10854,
          code: "TX12",
          title: "Materials, Structures, Mechanical Systems, and Manufacturing",
          priority: null,
        },
        {
          id: 10855,
          code: "TX12.1",
          title: "Materials",
          priority: null,
        },
        {
          id: 10857,
          code: "TX12.1.2",
          title: "Computational Materials",
          priority: null,
        },
      ],
      additionalTas: [
        {
          id: 10807,
          code: "TX11",
          title: "Software, Modeling, Simulation, and Information Processing",
          priority: null,
        },
        {
          id: 10840,
          code: "TX11.5",
          title:
            "Mission Architecture, Systems Analysis and Concept Development",
          priority: null,
        },
        {
          id: 10842,
          code: "TX11.5.2",
          title: "Tools and Methodologies for Performing Systems Analysis",
          priority: null,
        },
      ],
    },
  },
];

export default Projects